const String supabaseUrl = 'https://dhwgieeoqytcoyinkjpy.supabase.co';
const String anonKey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRod2dpZWVvcXl0Y295aW5ranB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTk1NTc2ODUsImV4cCI6MjAzNTEzMzY4NX0.FrsiGSkHRMFZHjz81RtVgOcuGiEiUEgqUmdH5_uk2DA';
